//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasiha.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nasiha.Resources.ModelsKeys", typeof(ModelsKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Ad Here.
        /// </summary>
        public static string AddYourAdHere {
            get {
                return ResourceManager.GetString("AddYourAdHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation new password do not match..
        /// </summary>
        public static string ConfirmNewPasswordMsg {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordErrorMsg {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure your email and password are correct, try again.
        /// </summary>
        public static string LoginProplem {
            get {
                return ResourceManager.GetString("LoginProplem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be under 100 chars.
        /// </summary>
        public static string Max100 {
            get {
                return ResourceManager.GetString("Max100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be under 50 chars.
        /// </summary>
        public static string Max50 {
            get {
                return ResourceManager.GetString("Max50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be under 500 chars.
        /// </summary>
        public static string Max500 {
            get {
                return ResourceManager.GetString("Max500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be 10 or greater 10 chars.
        /// </summary>
        public static string Min10 {
            get {
                return ResourceManager.GetString("Min10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be 4 or greater 4 chars.
        /// </summary>
        public static string Min4 {
            get {
                return ResourceManager.GetString("Min4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, your charcter should be 6 or greater 6 chars.
        /// </summary>
        public static string Min6 {
            get {
                return ResourceManager.GetString("Min6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry You have to Register with real email service, we accept &apos;gmail, yahoo, outlook, hotmail&apos; only..
        /// </summary>
        public static string RealEmailErrMsg {
            get {
                return ResourceManager.GetString("RealEmailErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is Required.
        /// </summary>
        public static string RequiredMsg {
            get {
                return ResourceManager.GetString("RequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this username isn&apos;t available at Now, try another.
        /// </summary>
        public static string UserNameNotAvailableMsg {
            get {
                return ResourceManager.GetString("UserNameNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name should have &quot;A - b&quot; and spaces ONLY.
        /// </summary>
        public static string VlaidFullNameMsg {
            get {
                return ResourceManager.GetString("VlaidFullNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UserName should have &quot;A - b&quot; and Numbers ONLY.
        /// </summary>
        public static string VlaidUserNameMsg {
            get {
                return ResourceManager.GetString("VlaidUserNameMsg", resourceCulture);
            }
        }
    }
}
