//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasiha.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nasiha.Resources.ViewsKeys", typeof(ViewsKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiha site, simply its just a way to make people give advices without make anothers feeling something like Shortage or any thing like this.
        /// </summary>
        public static string AboutMsg {
            get {
                return ResourceManager.GetString("AboutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and there is many and many of whomwant to order advices but they dont, because they think when do it this will make the another person better than hisself and this is wrong undrstant, our site come to change this wrong Concepts and help and this is our vision.
        /// </summary>
        public static string AboutMsg2 {
            get {
                return ResourceManager.GetString("AboutMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Nasiha.
        /// </summary>
        public static string AboutNasiha {
            get {
                return ResourceManager.GetString("AboutNasiha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Owner.
        /// </summary>
        public static string AddOwner {
            get {
                return ResourceManager.GetString("AddOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Admins.
        /// </summary>
        public static string AddToAdmins {
            get {
                return ResourceManager.GetString("AddToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Place.
        /// </summary>
        public static string AdPlace {
            get {
                return ResourceManager.GetString("AdPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Places.
        /// </summary>
        public static string AdsPlaces {
            get {
                return ResourceManager.GetString("AdsPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        public static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave Your Advice Here .
        /// </summary>
        public static string AdvicePlaceholder {
            get {
                return ResourceManager.GetString("AdvicePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advices.
        /// </summary>
        public static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiha.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiha.com.
        /// </summary>
        public static string AppNameCom {
            get {
                return ResourceManager.GetString("AppNameCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Advices.
        /// </summary>
        public static string BackToMessages {
            get {
                return ResourceManager.GetString("BackToMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile picture was updated Successfully.
        /// </summary>
        public static string ChangePictureSuccessMsg {
            get {
                return ResourceManager.GetString("ChangePictureSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Picture.
        /// </summary>
        public static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmEmail.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Your email confirmed succefully, Please.
        /// </summary>
        public static string ConfirmEmailSuccessMsg {
            get {
                return ResourceManager.GetString("ConfirmEmailSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, we would like to till you, we have compelete team and readt to replay about your  questions On Social Media Sites.
        /// </summary>
        public static string ContactMsg {
            get {
                return ResourceManager.GetString("ContactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your question and we wil replay to You directly.
        /// </summary>
        public static string ContactMsg2 {
            get {
                return ResourceManager.GetString("ContactMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this user For ever.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farouk Abdelhamid.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and Developd with.
        /// </summary>
        public static string DeveloperCopyrights {
            get {
                return ResourceManager.GetString("DeveloperCopyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Personal Information.
        /// </summary>
        public static string EditPersonalInformation {
            get {
                return ResourceManager.GetString("EditPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your informations had updated successfully.
        /// </summary>
        public static string EditPersonalInformationSuccessMsg {
            get {
                return ResourceManager.GetString("EditPersonalInformationSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found an error while we processing your request, and we are going to solve it.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Part Shown For Admins Onlay.
        /// </summary>
        public static string ForAdminsOnlay {
            get {
                return ResourceManager.GetString("ForAdminsOnlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string ForgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have Account? Login.
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiha It was the best place to share your advice with your friends or any body..
        /// </summary>
        public static string IntroMsg {
            get {
                return ResourceManager.GetString("IntroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        public static string Langauge {
            get {
                return ResourceManager.GetString("Langauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loved.
        /// </summary>
        public static string Liked {
            get {
                return ResourceManager.GetString("Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love It.
        /// </summary>
        public static string loveIt {
            get {
                return ResourceManager.GetString("loveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here You can Change your account settings.
        /// </summary>
        public static string ManageMsg {
            get {
                return ResourceManager.GetString("ManageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiha Team.
        /// </summary>
        public static string NasihaTeam {
            get {
                return ResourceManager.GetString("NasihaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ad.
        /// </summary>
        public static string NewAd {
            get {
                return ResourceManager.GetString("NewAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice To .
        /// </summary>
        public static string NewAdvice {
            get {
                return ResourceManager.GetString("NewAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Place.
        /// </summary>
        public static string NewPlace {
            get {
                return ResourceManager.GetString("NewPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Ads  on our Site Yet.
        /// </summary>
        public static string NoAdsMsg {
            get {
                return ResourceManager.GetString("NoAdsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry We do not found any ads places.
        /// </summary>
        public static string NoAdsPlacesYetMsg {
            get {
                return ResourceManager.GetString("NoAdsPlacesYetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ther is no Any Advices was sent to you before.
        /// </summary>
        public static string NoAdvices1 {
            get {
                return ResourceManager.GetString("NoAdvices1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try to share your account on social media sites and wait Advices.
        /// </summary>
        public static string NoAdvices2 {
            get {
                return ResourceManager.GetString("NoAdvices2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Advice on our Site Yet.
        /// </summary>
        public static string NoAdvicesOnSite {
            get {
                return ResourceManager.GetString("NoAdvicesOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Not Confirmed.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlineUsers.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Advantages.
        /// </summary>
        public static string OurAdvantages {
            get {
                return ResourceManager.GetString("OurAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin It.
        /// </summary>
        public static string pinIt {
            get {
                return ResourceManager.GetString("pinIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account to be able to reset your password on the future if you forgot it. going to your email and press confirm Button.
        /// </summary>
        public static string PleaseConfirmMsg {
            get {
                return ResourceManager.GetString("PleaseConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Of Current Ad.
        /// </summary>
        public static string PreviewOfCurrentAd {
            get {
                return ResourceManager.GetString("PreviewOfCurrentAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNew {
            get {
                return ResourceManager.GetString("RegisterAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this Advice.
        /// </summary>
        public static string RemoveAdviceWarning {
            get {
                return ResourceManager.GetString("RemoveAdviceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Admins.
        /// </summary>
        public static string RemoveFromAdmins {
            get {
                return ResourceManager.GetString("RemoveFromAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Owner.
        /// </summary>
        public static string RemoveOwner {
            get {
                return ResourceManager.GetString("RemoveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user for ever remember You cant restore user or his advices, be careful.
        /// </summary>
        public static string RemoveUserByAdminMsg {
            get {
                return ResourceManager.GetString("RemoveUserByAdminMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember: if you remove your account you cant restore it again.
        /// </summary>
        public static string RemoveUserdangerMsg {
            get {
                return ResourceManager.GetString("RemoveUserdangerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can delete this user and every thing related with him going to deleted too..
        /// </summary>
        public static string RemoveUserNote {
            get {
                return ResourceManager.GetString("RemoveUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry to see you leave :(.
        /// </summary>
        public static string RemoveUserSorryMsg {
            get {
                return ResourceManager.GetString("RemoveUserSorryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove your account for ever.
        /// </summary>
        public static string RemoveUserWarningMsg {
            get {
                return ResourceManager.GetString("RemoveUserWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string ResetPasswordSuccessConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseved.
        /// </summary>
        public static string Reseved {
            get {
                return ResourceManager.GetString("Reseved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry We dont find any user with this name, try again..
        /// </summary>
        public static string SearchResultZero1 {
            get {
                return ResourceManager.GetString("SearchResultZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not be Sad! together We can find him!.
        /// </summary>
        public static string SearchResultZero2 {
            get {
                return ResourceManager.GetString("SearchResultZero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent in.
        /// </summary>
        public static string SentIn {
            get {
                return ResourceManager.GetString("SentIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the best place to ask advice from your friends.
        /// </summary>
        public static string siteDescription {
            get {
                return ResourceManager.GetString("siteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sittings.
        /// </summary>
        public static string Sittings {
            get {
                return ResourceManager.GetString("Sittings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile To World, World SmileTo You.
        /// </summary>
        public static string Smile {
            get {
                return ResourceManager.GetString("Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry You cant to send advice to your self if you want to do this you can try to do it on real life.
        /// </summary>
        public static string SorryMsg {
            get {
                return ResourceManager.GetString("SorryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string SuccessChangePasswordMsg {
            get {
                return ResourceManager.GetString("SuccessChangePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThankU.
        /// </summary>
        public static string ThankU {
            get {
                return ResourceManager.GetString("ThankU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your good ethics, be sure Your message will change this person to better.
        /// </summary>
        public static string ThankUMsg {
            get {
                return ResourceManager.GetString("ThankUMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Ad On The follwing  Place.
        /// </summary>
        public static string ThisAdOnThisPlace {
            get {
                return ResourceManager.GetString("ThisAdOnThisPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TikTok.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Ad.
        /// </summary>
        public static string UpdateAd {
            get {
                return ResourceManager.GetString("UpdateAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Advices.
        /// </summary>
        public static string UserAdvices {
            get {
                return ResourceManager.GetString("UserAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advices were sent to this user since he Register.
        /// </summary>
        public static string UserMsgsCountNotice {
            get {
                return ResourceManager.GetString("UserMsgsCountNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message.
        /// </summary>
        public static string WarningMsg {
            get {
                return ResourceManager.GetString("WarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have to write something first.
        /// </summary>
        public static string WarningSearchQuery {
            get {
                return ResourceManager.GetString("WarningSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Us.
        /// </summary>
        public static string WhoUs {
            get {
                return ResourceManager.GetString("WhoUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
